'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { YNMark } from '@/components/YNLogo'

// ── Custom Cursor ──────────────────────────────────────────────────────────────
function CustomCursor() {
  const dotRef  = useRef<HTMLDivElement>(null)
  const ringRef = useRef<HTMLDivElement>(null)
  const mouse   = useRef({ x: -200, y: -200 })
  const ring    = useRef({ x: -200, y: -200 })

  useEffect(() => {
    const move = (e: MouseEvent) => { mouse.current = { x: e.clientX, y: e.clientY } }
    window.addEventListener('mousemove', move)
    let raf: number
    const loop = () => {
      if (dotRef.current) dotRef.current.style.transform = `translate(${mouse.current.x - 4}px,${mouse.current.y - 4}px)`
      ring.current.x += (mouse.current.x - ring.current.x) * 0.12
      ring.current.y += (mouse.current.y - ring.current.y) * 0.12
      if (ringRef.current) ringRef.current.style.transform = `translate(${ring.current.x - 16}px,${ring.current.y - 16}px)`
      raf = requestAnimationFrame(loop)
    }
    raf = requestAnimationFrame(loop)
    return () => { window.removeEventListener('mousemove', move); cancelAnimationFrame(raf) }
  }, [])

  return (
    <>
      <div ref={dotRef}  style={{ position:'fixed', top:0, left:0, width:8,  height:8,  borderRadius:'50%', background:'#00d4aa', pointerEvents:'none', zIndex:9999, willChange:'transform' }}/>
      <div ref={ringRef} style={{ position:'fixed', top:0, left:0, width:32, height:32, borderRadius:'50%', border:'1.5px solid rgba(0,212,170,.5)', pointerEvents:'none', zIndex:9998, willChange:'transform' }}/>
    </>
  )
}

const PAST_REPORTS = [
  { title:'April 2026 Congressional Alpha Report',      date:'Apr 30, 2026',  teaser:'43 new purchase transactions filed. Defense and energy sectors dominated. One senator bought $2M in defense before a budget vote.',       color:'#00d4aa', tag:'CONGRESSIONAL' },
  { title:'Q1 2026 Earnings Integrity Index',           date:'Apr 5, 2026',   teaser:'We scored 340 S&P 500 earnings calls. 62% showed narrative-reality divergence. Top 10 most honest and most dishonest management teams.',    color:'#1e90ff', tag:'EARNINGS' },
  { title:'March 2026 Smart Money Monthly',             date:'Mar 31, 2026',  teaser:'Insider purchases hit 18-month high. Options anomalies fired 47 times — 31 were profitable within 5 trading days.',                         color:'#a855f7', tag:'SMART MONEY' },
  { title:'February 2026 Congressional Alpha Report',   date:'Feb 28, 2026',  teaser:'Senate tech purchases up 34% ahead of AI regulation hearings. Average 30-day return on flagged trades: +9.2%.',                            color:'#00d4aa', tag:'CONGRESSIONAL' },
  { title:'Q4 2025 Earnings Integrity Index',           date:'Jan 15, 2026',  teaser:'Full-year honesty rankings across all S&P 500 companies. Most consistent truth-tellers vs. chronic spin artists.',                          color:'#1e90ff', tag:'EARNINGS' },
  { title:'January 2026 Smart Money Monthly',           date:'Jan 31, 2026',  teaser:'January effect plays, institutional rebalancing flows, and 5 insider conviction buys that outperformed by double digits.',                  color:'#a855f7', tag:'SMART MONEY' },
]

const SERIES = [
  {
    name:     'Congressional Alpha Report',
    freq:     'Monthly',
    icon:     '🏛',
    color:    '#00d4aa',
    desc:     'We track every House and Senate financial disclosure. This report quantifies the alpha generated by trading alongside — or against — congressional positions. Which sectors did lawmakers favor? Which committees bought before legislation? The data is public. The edge is not.',
  },
  {
    name:     'Smart Money Monthly',
    freq:     'Monthly',
    icon:     '💰',
    color:    '#a855f7',
    desc:     'Insider purchase transactions, unusual options activity, and signal convergence events from the past 30 days. Which signals fired? What happened next? We track the hit rates, the false positives, and the single best trade from each month.',
  },
  {
    name:     'Earnings Integrity Index',
    freq:     'Quarterly',
    icon:     '📊',
    color:    '#1e90ff',
    desc:     'We score every major company\'s management honesty across 4 quarters of earnings calls. Who\'s telling the truth? Who\'s spinning? Divergence scores, red flag counts, and the quarterly rankings of America\'s most and least trustworthy CEOs.',
  },
]

export default function ResearchPage() {
  const [email, setEmail]       = useState('')
  const [subscribed, setSubscribed] = useState(false)
  const [submitting, setSubmitting] = useState(false)

  function handleSubscribe(e: React.FormEvent) {
    e.preventDefault()
    if (!email) return
    setSubmitting(true)
    setTimeout(() => { setSubmitting(false); setSubscribed(true) }, 1000)
  }

  return (
    <div style={{ background:'#030a10', minHeight:'100vh', color:'#e8f4f8', fontFamily:'"Inter",system-ui,-apple-system,sans-serif' }}>
      <style>{`
        @keyframes fadeUp  { from { opacity:0; transform:translateY(20px) } to { opacity:1; transform:translateY(0) } }
        @keyframes shimmer { from { background-position:200% center } to { background-position:-200% center } }
        * { box-sizing:border-box; margin:0; padding:0 }
        ::selection { background:#00d4aa40 }
        @media(max-width:768px) {
          .hero-title  { font-size:38px !important }
          .series-grid { flex-direction:column !important }
          .past-grid   { grid-template-columns:1fr !important }
        }
      `}</style>

      <CustomCursor />

      {/* NAV */}
      <nav style={{
        position:'sticky', top:0, zIndex:100,
        background:'rgba(3,10,16,.92)', backdropFilter:'blur(12px)',
        borderBottom:'1px solid rgba(255,255,255,.06)',
        padding:'0 24px', height:60,
        display:'flex', alignItems:'center', justifyContent:'space-between',
      }}>
        <div style={{ display:'flex', alignItems:'center', gap:16 }}>
          <Link href="/" style={{ display:'flex', alignItems:'center', gap:10, textDecoration:'none' }}>
            <YNMark size={28} glow />
            <span style={{ fontSize:14, fontWeight:700, color:'#fff', letterSpacing:'-0.02em' }}>YN Finance</span>
          </Link>
          <div style={{ width:1, height:20, background:'rgba(255,255,255,.12)' }}/>
          <span style={{ fontSize:11, fontWeight:700, letterSpacing:'0.18em', color:'#00d4aa', fontFamily:'monospace' }}>RESEARCH</span>
        </div>
        <div style={{ display:'flex', alignItems:'center', gap:16 }}>
          <Link href="/intel" style={{ fontSize:12, color:'#6a90a8', textDecoration:'none', fontFamily:'monospace', letterSpacing:'0.08em' }}>Intelligence →</Link>
          <Link href="/" style={{
            fontSize:12, color:'#6a90a8', textDecoration:'none', fontFamily:'monospace',
            letterSpacing:'0.08em', padding:'6px 12px',
            border:'1px solid rgba(255,255,255,.08)', borderRadius:6,
          }}>
            ← Home
          </Link>
        </div>
      </nav>

      {/* HERO */}
      <div style={{ padding:'100px 24px 80px', maxWidth:900, margin:'0 auto', textAlign:'center', animation:'fadeUp .6s ease both' }}>
        <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.2em', color:'#00d4aa', fontFamily:'monospace', marginBottom:20, opacity:0.8 }}>
          FREE · PUBLIC DATA · AI-POWERED ANALYSIS
        </div>
        <h1 className="hero-title" style={{
          fontSize:54, fontWeight:900, lineHeight:1.05, letterSpacing:'-0.03em',
          background:'linear-gradient(135deg,#e8f4f8 0%,#00d4aa 50%,#1e90ff 100%)',
          WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text',
          marginBottom:24,
        }}>
          YN Finance Research —<br />The intelligence reports Wall Street<br />doesn&apos;t publish.
        </h1>
        <p style={{ fontSize:17, color:'#7a9aaa', lineHeight:1.7, maxWidth:600, margin:'0 auto' }}>
          Monthly analysis of congressional trading patterns, smart money movements, and earnings integrity. Free. Always.
        </p>
      </div>

      {/* FEATURED REPORT */}
      <div style={{ padding:'0 24px 80px', maxWidth:1000, margin:'0 auto' }}>
        <div style={{
          background:'linear-gradient(135deg,rgba(0,212,170,.07),rgba(30,144,255,.05))',
          border:'1px solid rgba(0,212,170,.25)', borderRadius:20, padding:'48px',
          animation:'fadeUp .5s ease .1s both', position:'relative', overflow:'hidden',
        }}>
          {/* Background accent */}
          <div style={{
            position:'absolute', top:-60, right:-60, width:300, height:300,
            borderRadius:'50%', background:'radial-gradient(circle,rgba(0,212,170,.08),transparent 70%)',
            pointerEvents:'none',
          }}/>

          <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:24, flexWrap:'wrap' }}>
            <span style={{
              fontSize:10, fontWeight:800, letterSpacing:'0.16em',
              background:'linear-gradient(135deg,#00d4aa,#1e90ff)',
              color:'#030a10', padding:'4px 12px', borderRadius:10,
            }}>LATEST REPORT</span>
            <span style={{ fontSize:11, color:'#6a90a8', fontFamily:'monospace' }}>May 2026</span>
          </div>

          <h2 style={{ fontSize:32, fontWeight:900, letterSpacing:'-0.02em', color:'#e8f4f8', marginBottom:12 }}>
            Congressional Alpha Report — May 2026
          </h2>
          <p style={{ fontSize:16, color:'#7a9aaa', lineHeight:1.6, marginBottom:36 }}>
            We analyzed 847 congressional stock trades filed in 2026. Here&apos;s what we found.
          </p>

          <div style={{ display:'flex', flexDirection:'column', gap:16, marginBottom:40 }}>
            {[
              { stat:'+4.2%',  text:'Members of Congress outperformed the S&P 500 by an average of 4.2% on purchase trades' },
              { stat:'+8.7%',  text:'Defense stocks bought before budget votes averaged +8.7% in the following 30 days' },
              { stat:'+12.3%', text:'Technology purchases ahead of committee hearings averaged +12.3%' },
            ].map((f, i) => (
              <div key={i} style={{ display:'flex', alignItems:'flex-start', gap:16 }}>
                <div style={{
                  flexShrink:0, width:60, height:32,
                  display:'flex', alignItems:'center', justifyContent:'center',
                  background:'rgba(0,212,170,.12)', border:'1px solid rgba(0,212,170,.25)',
                  borderRadius:8,
                }}>
                  <span style={{ fontSize:13, fontWeight:800, color:'#00d4aa', fontFamily:'monospace' }}>{f.stat}</span>
                </div>
                <p style={{ fontSize:15, color:'#c8e4e8', lineHeight:1.6 }}>{f.text}</p>
              </div>
            ))}
          </div>

          <button style={{
            display:'inline-flex', alignItems:'center', gap:8,
            background:'linear-gradient(135deg,#00d4aa,#1e90ff)',
            color:'#030a10', fontWeight:800, fontSize:14, letterSpacing:'0.04em',
            padding:'12px 28px', borderRadius:10, border:'none', cursor:'pointer',
            boxShadow:'0 0 30px rgba(0,212,170,.2)',
          }}>
            Read Full Report →
          </button>
        </div>
      </div>

      {/* RESEARCH SERIES */}
      <div style={{ padding:'0 24px 80px', maxWidth:1000, margin:'0 auto' }}>
        <div style={{ textAlign:'center', marginBottom:48 }}>
          <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.2em', color:'#a855f7', fontFamily:'monospace', marginBottom:14 }}>ONGOING SERIES</div>
          <h2 style={{ fontSize:34, fontWeight:900, letterSpacing:'-0.03em', color:'#e8f4f8' }}>Research Series</h2>
        </div>
        <div className="series-grid" style={{ display:'flex', gap:20 }}>
          {SERIES.map((s, i) => (
            <div key={i} style={{
              flex:1, padding:'32px 28px',
              background:'rgba(255,255,255,.025)',
              border:`1px solid rgba(255,255,255,.08)`,
              borderRadius:16,
              animation:`fadeUp .5s ease ${0.1 * i}s both`,
              transition:'border-color .2s, transform .2s',
            }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = `${s.color}50`; e.currentTarget.style.transform = 'translateY(-3px)' }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(255,255,255,.08)'; e.currentTarget.style.transform = 'none' }}
            >
              <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:20 }}>
                <span style={{ fontSize:28 }}>{s.icon}</span>
                <div>
                  <div style={{ fontSize:14, fontWeight:700, color:'#e8f4f8' }}>{s.name}</div>
                  <div style={{
                    fontSize:10, fontWeight:700, letterSpacing:'0.14em',
                    color: s.color, fontFamily:'monospace', marginTop:3,
                  }}>{s.freq.toUpperCase()}</div>
                </div>
              </div>
              <p style={{ fontSize:14, color:'#7a9aaa', lineHeight:1.7 }}>{s.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* PAST REPORTS */}
      <div style={{ padding:'0 24px 80px', maxWidth:1000, margin:'0 auto' }}>
        <div style={{ textAlign:'center', marginBottom:48 }}>
          <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.2em', color:'#1e90ff', fontFamily:'monospace', marginBottom:14 }}>ARCHIVE</div>
          <h2 style={{ fontSize:34, fontWeight:900, letterSpacing:'-0.03em', color:'#e8f4f8' }}>Past Reports</h2>
        </div>
        <div className="past-grid" style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:16 }}>
          {PAST_REPORTS.map((r, i) => (
            <div key={i} style={{
              padding:'24px 26px',
              background:'rgba(255,255,255,.025)',
              border:'1px solid rgba(255,255,255,.07)',
              borderRadius:14,
              animation:`fadeUp .5s ease ${0.07 * i}s both`,
              transition:'border-color .2s',
            }}
              onMouseEnter={e => (e.currentTarget.style.borderColor = `${r.color}40`)}
              onMouseLeave={e => (e.currentTarget.style.borderColor = 'rgba(255,255,255,.07)')}
            >
              <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:12 }}>
                <span style={{
                  fontSize:9, fontWeight:800, letterSpacing:'0.14em',
                  color: r.color, background:`${r.color}15`,
                  border:`1px solid ${r.color}35`,
                  borderRadius:5, padding:'2px 8px', fontFamily:'monospace',
                }}>
                  {r.tag}
                </span>
                <span style={{ fontSize:11, color:'#4a6a7a', fontFamily:'monospace' }}>{r.date}</span>
              </div>
              <h3 style={{ fontSize:15, fontWeight:700, color:'#e8f4f8', marginBottom:10, lineHeight:1.3 }}>{r.title}</h3>
              <p style={{ fontSize:13, color:'#6a90a8', lineHeight:1.6, marginBottom:18 }}>{r.teaser}</p>
              <button style={{
                fontSize:12, fontWeight:700, letterSpacing:'0.08em',
                color:'#4a6a7a', background:'rgba(255,255,255,.04)',
                border:'1px solid rgba(255,255,255,.09)',
                borderRadius:7, padding:'7px 14px', cursor:'not-allowed',
                fontFamily:'monospace',
              }}>
                Coming Soon
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* SUBSCRIBE */}
      <div style={{ padding:'0 24px 80px', maxWidth:700, margin:'0 auto', textAlign:'center' }}>
        <div style={{
          background:'rgba(255,255,255,.025)', border:'1px solid rgba(255,255,255,.08)',
          borderRadius:20, padding:'56px 48px',
        }}>
          <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.2em', color:'#00d4aa', fontFamily:'monospace', marginBottom:20 }}>NEWSLETTER</div>
          <h2 style={{ fontSize:28, fontWeight:900, letterSpacing:'-0.02em', color:'#e8f4f8', marginBottom:14 }}>
            Get reports in your inbox the day they publish.
          </h2>
          <p style={{ fontSize:15, color:'#6a90a8', lineHeight:1.7, marginBottom:36 }}>
            Free, monthly. No spam. Unsubscribe any time.
          </p>

          {subscribed ? (
            <div style={{
              padding:'20px 28px', background:'rgba(0,212,170,.1)',
              border:'1px solid rgba(0,212,170,.3)', borderRadius:12,
              fontSize:15, fontWeight:700, color:'#00d4aa',
            }}>
              You&apos;re subscribed. First report coming soon.
            </div>
          ) : (
            <form onSubmit={handleSubscribe} style={{ display:'flex', gap:12, maxWidth:440, margin:'0 auto', flexWrap:'wrap', justifyContent:'center' }}>
              <input
                type="email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                placeholder="your@email.com"
                required
                style={{
                  flex:1, minWidth:220, padding:'12px 18px', borderRadius:10,
                  background:'rgba(255,255,255,.05)', border:'1px solid rgba(255,255,255,.14)',
                  color:'#e8f4f8', fontSize:14, outline:'none', fontFamily:'inherit',
                }}
              />
              <button type="submit" disabled={submitting} style={{
                padding:'12px 24px', borderRadius:10,
                background:'linear-gradient(135deg,#00d4aa,#1e90ff)',
                color:'#030a10', fontWeight:800, fontSize:14,
                border:'none', cursor: submitting ? 'wait' : 'pointer',
                letterSpacing:'0.04em',
              }}>
                {submitting ? '...' : 'Subscribe'}
              </button>
            </form>
          )}
        </div>
      </div>

      {/* METHODOLOGY */}
      <div style={{ padding:'0 24px 120px', maxWidth:800, margin:'0 auto' }}>
        <div style={{ textAlign:'center', marginBottom:48 }}>
          <div style={{ fontSize:11, fontWeight:700, letterSpacing:'0.2em', color:'#6a90a8', fontFamily:'monospace', marginBottom:14 }}>TRANSPARENCY</div>
          <h2 style={{ fontSize:28, fontWeight:900, letterSpacing:'-0.02em', color:'#e8f4f8' }}>Methodology</h2>
        </div>
        <div style={{ display:'flex', flexDirection:'column', gap:20 }}>
          {[
            { step:'01', title:'Public Data Sources', desc:'All data comes from public sources: SEC EDGAR filings, House and Senate financial disclosure portals, CBOE options data, Finnhub market feeds, and government press releases. We do not use non-public information.' },
            { step:'02', title:'AI Analysis',         desc:'Raw data is processed by Gemini 2.0 Flash trained on our proprietary analytical frameworks. The AI scores divergence, calculates statistical edge, and generates plain-language summaries of the key findings.' },
            { step:'03', title:'Human Review',        desc:'Every report is reviewed by our editorial team before publication. We flag model uncertainty, verify statistics independently, and add context that AI analysis misses. We correct errors promptly and transparently.' },
          ].map((m, i) => (
            <div key={i} style={{
              display:'flex', gap:24, alignItems:'flex-start',
              padding:'24px 28px',
              background:'rgba(255,255,255,.025)',
              border:'1px solid rgba(255,255,255,.07)', borderRadius:14,
              animation:`fadeUp .5s ease ${0.1 * i}s both`,
            }}>
              <div style={{
                flexShrink:0, width:44, height:44,
                display:'flex', alignItems:'center', justifyContent:'center',
                background:'rgba(0,212,170,.1)', border:'1px solid rgba(0,212,170,.2)',
                borderRadius:10,
              }}>
                <span style={{ fontSize:12, fontWeight:800, color:'#00d4aa', fontFamily:'monospace' }}>{m.step}</span>
              </div>
              <div>
                <div style={{ fontSize:15, fontWeight:700, color:'#e8f4f8', marginBottom:8 }}>{m.title}</div>
                <p style={{ fontSize:14, color:'#7a9aaa', lineHeight:1.7 }}>{m.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
