// AUTO-GENERATED by scripts/montecarlo-algos.mjs — do not edit by hand. Re-run the script to refresh.
export interface MonteCarloRow {
  rank: number; id: string; name: string
  win: number; R: number; expR: number
  passRate: number; bustRate: number
  medReturn: number; p95MaxDD: number; score: number
}
export interface MonteCarloMeta {
  trials: number; riskPct: number; profitTarget: number
  maxDrawdown: number; maxTrades: number; generated: string
}
export const MONTE_CARLO_META: MonteCarloMeta = {
  "trials": 20000,
  "riskPct": 0.005,
  "profitTarget": 0.08,
  "maxDrawdown": 0.06,
  "maxTrades": 120,
  "generated": "2026-06-22"
}

export const MONTE_CARLO: MonteCarloRow[] = [
  {
    "rank": 1,
    "id": "nqtrendpb",
    "name": "Trend Pullback (TS-Momentum)",
    "win": 0.415,
    "R": 1.8,
    "expR": 0.162,
    "passRate": 0.6639,
    "bustRate": 0.2391,
    "medReturn": 0.0818,
    "p95MaxDD": 0.0637,
    "score": 0.5934
  },
  {
    "rank": 2,
    "id": "nqmeanrev",
    "name": "RSI-2 Mean Reversion",
    "win": 0.575,
    "R": 0.9,
    "expR": 0.0925,
    "passRate": 0.4288,
    "bustRate": 0.129,
    "medReturn": 0.0557,
    "p95MaxDD": 0.0623,
    "score": 0.3684
  },
  {
    "rank": 3,
    "id": "nqorb",
    "name": "Opening-Range Breakout",
    "win": 0.375,
    "R": 1.8,
    "expR": 0.05,
    "passRate": 0.3689,
    "bustRate": 0.4943,
    "medReturn": 0.0053,
    "p95MaxDD": 0.0643,
    "score": 0.1472
  }
]
