// AUTO-GENERATED by scripts/montecarlo-algos.mjs — do not edit by hand. Re-run the script to refresh.
export interface MonteCarloRow {
  rank: number; id: string; name: string
  win: number; R: number; expR: number
  passRate: number; bustRate: number
  medReturn: number; p95MaxDD: number; score: number
}
export interface MonteCarloMeta {
  trials: number; riskPct: number; profitTarget: number
  maxDrawdown: number; maxTrades: number; generated: string
}
export const MONTE_CARLO_META: MonteCarloMeta = {
  "trials": 20000,
  "riskPct": 0.02,
  "profitTarget": 0.1,
  "maxDrawdown": 0.06,
  "maxTrades": 60,
  "generated": "2026-06-22"
}

export const MONTE_CARLO: MonteCarloRow[] = [
  {
    "rank": 1,
    "id": "nqstophunt",
    "name": "Liquidity Stop-Hunt Rev.",
    "win": 0.605,
    "R": 2.16,
    "expR": 0.9118,
    "passRate": 0.9056,
    "bustRate": 0.0944,
    "medReturn": 0.1168,
    "p95MaxDD": 0.0776,
    "score": 0.7698
  },
  {
    "rank": 2,
    "id": "nqkz",
    "name": "London–NY Killzone Sweep",
    "win": 0.565,
    "R": 2.07,
    "expR": 0.7345,
    "passRate": 0.8566,
    "bustRate": 0.1434,
    "medReturn": 0.107,
    "p95MaxDD": 0.0776,
    "score": 0.6698
  },
  {
    "rank": 3,
    "id": "nqdiv",
    "name": "RSI Divergence Reversal",
    "win": 0.555,
    "R": 1.8,
    "expR": 0.554,
    "passRate": 0.7783,
    "bustRate": 0.2217,
    "medReturn": 0.1064,
    "p95MaxDD": 0.0776,
    "score": 0.5439
  },
  {
    "rank": 4,
    "id": "nqfib",
    "name": "Fib 61.8 Trend Pullback",
    "win": 0.545,
    "R": 1.8,
    "expR": 0.526,
    "passRate": 0.7645,
    "bustRate": 0.2354,
    "medReturn": 0.1063,
    "p95MaxDD": 0.0776,
    "score": 0.5229
  },
  {
    "rank": 5,
    "id": "nqbos",
    "name": "Break-of-Structure Cont.",
    "win": 0.475,
    "R": 2.34,
    "expR": 0.5865,
    "passRate": 0.7312,
    "bustRate": 0.2687,
    "medReturn": 0.1075,
    "p95MaxDD": 0.0776,
    "score": 0.5145
  },
  {
    "rank": 6,
    "id": "nqpivot",
    "name": "Floor Pivot Reversion",
    "win": 0.645,
    "R": 1.08,
    "expR": 0.3416,
    "passRate": 0.806,
    "bustRate": 0.1941,
    "medReturn": 0.1141,
    "p95MaxDD": 0.0776,
    "score": 0.4975
  },
  {
    "rank": 7,
    "id": "nqcloud",
    "name": "200-EMA Cloud Pullback",
    "win": 0.515,
    "R": 1.98,
    "expR": 0.5347,
    "passRate": 0.7312,
    "bustRate": 0.2688,
    "medReturn": 0.1183,
    "p95MaxDD": 0.0776,
    "score": 0.4974
  },
  {
    "rank": 8,
    "id": "nqgapgo",
    "name": "Gap-and-Go Continuation",
    "win": 0.525,
    "R": 1.8,
    "expR": 0.47,
    "passRate": 0.7195,
    "bustRate": 0.2806,
    "medReturn": 0.1063,
    "p95MaxDD": 0.0776,
    "score": 0.4662
  },
  {
    "rank": 9,
    "id": "nq3bar",
    "name": "3-Bar Reversal at Band",
    "win": 0.585,
    "R": 1.35,
    "expR": 0.3747,
    "passRate": 0.741,
    "bustRate": 0.259,
    "medReturn": 0.1115,
    "p95MaxDD": 0.0776,
    "score": 0.4532
  },
  {
    "rank": 10,
    "id": "nqcvd",
    "name": "Delta Divergence",
    "win": 0.535,
    "R": 1.62,
    "expR": 0.4017,
    "passRate": 0.7093,
    "bustRate": 0.2908,
    "medReturn": 0.1039,
    "p95MaxDD": 0.0776,
    "score": 0.435
  },
  {
    "rank": 11,
    "id": "nqmomo",
    "name": "Momentum Ignition",
    "win": 0.495,
    "R": 1.98,
    "expR": 0.4751,
    "passRate": 0.6768,
    "bustRate": 0.3231,
    "medReturn": 0.1011,
    "p95MaxDD": 0.0776,
    "score": 0.4316
  },
  {
    "rank": 12,
    "id": "nqsupertrend",
    "name": "SuperTrend + ADX Flip",
    "win": 0.495,
    "R": 1.98,
    "expR": 0.4751,
    "passRate": 0.6762,
    "bustRate": 0.3238,
    "medReturn": 0.1011,
    "p95MaxDD": 0.0776,
    "score": 0.4311
  },
  {
    "rank": 13,
    "id": "nqkelt",
    "name": "Keltner Squeeze Release",
    "win": 0.455,
    "R": 2.25,
    "expR": 0.4788,
    "passRate": 0.6584,
    "bustRate": 0.3416,
    "medReturn": 0.1183,
    "p95MaxDD": 0.0776,
    "score": 0.4172
  },
  {
    "rank": 14,
    "id": "nqturtle",
    "name": "Donchian Turtle Breakout",
    "win": 0.405,
    "R": 2.7,
    "expR": 0.4985,
    "passRate": 0.6387,
    "bustRate": 0.3613,
    "medReturn": 0.1109,
    "p95MaxDD": 0.0776,
    "score": 0.4069
  },
  {
    "rank": 15,
    "id": "nqzfade",
    "name": "Volatility Z-Score Fade",
    "win": 0.665,
    "R": 0.9,
    "expR": 0.2635,
    "passRate": 0.7059,
    "bustRate": 0.294,
    "medReturn": 0.1051,
    "p95MaxDD": 0.0776,
    "score": 0.3868
  }
]
