'use client'

import { useState, useEffect } from 'react'
import { RefreshCw, Bot, Newspaper } from 'lucide-react'

interface Section { title: string; icon: string; content: string }
interface NewspaperData {
  headline: string
  subheadline: string
  edition: string
  sections: Section[]
  marketSentiment: 'BULLISH' | 'BEARISH' | 'NEUTRAL' | 'CAUTIOUS'
  traderTip: string
  generatedAt: string
  date: string
}

const SENTIMENT_COLOR = { BULLISH: '#00d4aa', BEARISH: '#ff4757', NEUTRAL: '#ffa502', CAUTIOUS: '#ffa502' }
const CACHE_KEY = 'yn_newspaper'

function getCacheKey() {
  // Regenerate after 5 AM PST each day
  const pst = new Date(new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }))
  const dateStr = pst.toDateString()
  const hour = pst.getHours()
  return hour >= 5 ? `${dateStr}_am` : `${new Date(pst.getTime() - 86400000).toDateString()}_am`
}

export default function AINewspaper() {
  const [paper, setPaper] = useState<NewspaperData | null>(null)
  const [loading, setLoading] = useState(true)

  const load = async (force = false) => {
    setLoading(true)
    const key = getCacheKey()
    if (!force) {
      try {
        const cached = JSON.parse(localStorage.getItem(CACHE_KEY) || '{}')
        if (cached.key === key && cached.data) {
          setPaper(cached.data)
          setLoading(false)
          return
        }
      } catch {}
    }
    try {
      const res = await fetch('/api/newspaper')
      const json = await res.json()
      if (json.newspaper) {
        setPaper(json.newspaper)
        localStorage.setItem(CACHE_KEY, JSON.stringify({ key, data: json.newspaper }))
      }
    } catch {}
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  if (loading) return (
    <div style={{ padding: 32, textAlign: 'center' }}>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 10, fontSize: 12, color: '#4a5e7a' }}>
        <Newspaper size={16} color="#a855f7" />
        <span>Generating today&apos;s AI newspaper with live market data...</span>
      </div>
    </div>
  )

  if (!paper) return (
    <div style={{ padding: 32, textAlign: 'center', fontSize: 12, color: '#4a5e7a' }}>
      Add FINNHUB_API_KEY + GEMINI_API_KEY to Netlify to enable the AI newspaper.
    </div>
  )

  const sentimentColor = SENTIMENT_COLOR[paper.marketSentiment] || '#ffa502'

  return (
    <div style={{ fontFamily: '"Playfair Display", "Times New Roman", serif', color: '#cdd6f4', maxWidth: 800, margin: '0 auto', padding: '0 16px 32px' }}>
      {/* Masthead */}
      <div style={{ borderBottom: '3px solid #cdd6f4', borderTop: '3px solid #cdd6f4', padding: '16px 0 12px', marginBottom: 20, textAlign: 'center', position: 'relative' }}>
        <div style={{ fontSize: 9, fontFamily: 'Inter, sans-serif', color: '#4a5e7a', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: 8 }}>
          {paper.date} · {paper.edition} · AI-Generated by Gemini
        </div>
        <h1 style={{ fontSize: 'clamp(28px, 5vw, 48px)', fontWeight: 900, color: '#fff', letterSpacing: -1, lineHeight: 1, margin: '0 0 4px' }}>
          YN Finance Daily
        </h1>
        <div style={{ fontSize: 11, fontFamily: 'Inter, sans-serif', color: '#4a5e7a', fontStyle: 'italic' }}>
          The AI-powered voice of the markets — Updated every morning at 5:00 AM PST
        </div>

        {/* Sentiment badge */}
        <div style={{ position: 'absolute', right: 0, top: '50%', transform: 'translateY(-50%)', textAlign: 'center' }}>
          <div style={{ fontSize: 9, fontFamily: 'Inter, sans-serif', color: '#4a5e7a', marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Sentiment</div>
          <div style={{ fontSize: 13, fontWeight: 900, fontFamily: 'Inter, sans-serif', color: sentimentColor }}>{paper.marketSentiment}</div>
        </div>

        <button onClick={() => load(true)}
          style={{ position: 'absolute', left: 0, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: '#4a5e7a', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4, fontSize: 10, fontFamily: 'Inter, sans-serif' }}>
          <RefreshCw size={11} /> Refresh
        </button>
      </div>

      {/* Front page headline */}
      <div style={{ textAlign: 'center', marginBottom: 24, paddingBottom: 20, borderBottom: '1px solid #1a2d4a' }}>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 9, fontFamily: 'Inter, sans-serif', color: sentimentColor, textTransform: 'uppercase', letterSpacing: '0.15em', fontWeight: 700, marginBottom: 10, background: `${sentimentColor}15`, padding: '4px 12px', borderRadius: 4 }}>
          <Bot size={10} /> AI Analysis
        </div>
        <h2 style={{ fontSize: 'clamp(20px, 3vw, 30px)', fontWeight: 900, color: '#fff', lineHeight: 1.2, margin: '0 0 10px', letterSpacing: -0.5 }}>
          {paper.headline}
        </h2>
        <p style={{ fontSize: 14, color: '#7f93b5', fontStyle: 'italic', margin: 0 }}>{paper.subheadline}</p>
      </div>

      {/* Trader tip banner */}
      <div style={{ background: `${sentimentColor}10`, border: `1px solid ${sentimentColor}30`, borderRadius: 8, padding: '10px 16px', marginBottom: 24, display: 'flex', alignItems: 'center', gap: 10 }}>
        <span style={{ fontSize: 16 }}>💡</span>
        <div>
          <div style={{ fontSize: 9, fontFamily: 'Inter, sans-serif', color: sentimentColor, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 3 }}>Today&apos;s Trader Tip</div>
          <p style={{ fontSize: 12, color: '#cdd6f4', margin: 0, fontFamily: 'Inter, sans-serif' }}>{paper.traderTip}</p>
        </div>
      </div>

      {/* Sections */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
        {paper.sections?.map((section, i) => (
          <div key={i} style={{ borderTop: '2px solid #1a2d4a', paddingTop: 14, gridColumn: i === 1 ? '1 / -1' : 'auto' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10 }}>
              <span style={{ fontSize: 16 }}>{section.icon}</span>
              <h3 style={{ fontSize: 11, fontFamily: 'Inter, sans-serif', fontWeight: 800, color: '#7f93b5', textTransform: 'uppercase', letterSpacing: '0.12em', margin: 0 }}>
                {section.title}
              </h3>
            </div>
            <p style={{ fontSize: 13, color: '#cdd6f4', lineHeight: 1.8, margin: 0 }}>
              {section.content}
            </p>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 24, paddingTop: 12, borderTop: '1px solid #1a2d4a', textAlign: 'center', fontSize: 9, color: '#4a5e7a', fontFamily: 'Inter, sans-serif' }}>
        Generated by Gemini AI using live Finnhub market data · Not financial advice · For educational purposes only
        {paper.generatedAt && ` · Generated ${new Date(paper.generatedAt).toLocaleTimeString()}`}
      </div>
    </div>
  )
}
